export const NavItems = [
  {
    name: "Home",
    link: "/",
    id: "home",
  },
  { name: "About", link: "/about", id: "about" },
  { name: "Shop", link: "/shop", id: "shop" },
  { name: "contact", link: "/contact", id: "contact" },
];

export const heroImages = [
  {
    img: "https://images.unsplash.com/photo-1601121141461-920cb1993441?q=80&w=1099&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",

    active: "hidden",
  },
  {
    img: "https://images.unsplash.com/photo-1633810543462-77c4a3b13f07?q=80&w=1064&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",

    active: "hidden",
  },
  {
    img: "https://plus.unsplash.com/premium_photo-1709033404514-c3953af680b4?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    active: "hidden",
  },
  {
    img: "https://images.unsplash.com/photo-1608613381851-6a058de0dc11?q=80&w=1211&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    active: "",
  },
];

export const category = [
  {
    name: "Vase",
    href: "###",
    image: "fa-solid fa-bottle-droplet",
    color: "bg-yellow-700",
  },
  {
    name: "Bowl",
    href: "###",
    image: "fa-solid fa-bowl-rice",
    color: "bg-yellow-300",
  },
  {
    name: "Mugs",
    href: "###",
    image: "fa-solid fa-mug-hot",
    color: "bg-yellow-900",
  },
];

export const about = [
  { header: "Expertly Crafted Pottery by Hand Since 1990" },
  { header: "We Offer Premium Pottery Products" },
];

export const contact = [
  {
    name: "Email",
    icon: "fa-solid fa-envelope",
    details: "LoremIpsum@gmail.com",
  },
  {
    name: "Location",
    icon: "fa-solid fa-location-dot",
    details: "2, Lorem ipsum street, Cambridge, United Kingdom.",
  },
  {
    name: "Call",
    icon: "fa-solid fa-phone",
    details: "+123 456 789",
  },
];

export const store = [
  {
    quantity: "10",
    name: "Classic Elegance Mug",
    price: 91.49,
    category: "Mug",
    color: "White",
    img: "https://images.unsplash.com/photo-1616241673347-67fb5dfa3167?q=80&w=428&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    quantity: "10",
    name: "Modern Simplicity Cup",
    price: 54.19,
    category: "Mug",
    color: "White",
    img: "https://images.unsplash.com/photo-1520485521983-bfaa0bc6c80e?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    quantity: "10",
    name: "Snowy Day Mug",
    price: 73.46,
    category: "Mug",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Ocean Breeze Cup",
    price: 68.29,
    category: "Mug",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Azure Sky Mug",
    price: 96.65,
    category: "Mug",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Deep Sea Cup",
    price: 87.56,
    category: "Mug",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunny Morning Mug",
    price: 87.39,
    category: "Mug",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Golden Glow Cup",
    price: 54.29,
    category: "Mug",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Lemon Zest Mug",
    price: 82.51,
    category: "Mug",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunshine Delight Cup",
    price: 93.61,
    category: "Mug",
    color: "Yellow",
    img: "",
  },

  {
    quantity: "10",
    name: "Classic Elegance Bowl",
    price: 87.05,
    category: "Bowl",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Modern Simplicity Bowl",
    price: 57.24,
    category: "Bowl",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Snowy Day Bowl",
    price: 81.57,
    category: "Bowl",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Ocean Breeze Bowl",
    price: 58.61,
    category: "Bowl",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Azure Sky Bowl",
    price: 56.6,
    category: "Bowl",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Deep Sea Bowl",
    price: 61.83,
    category: "Bowl",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunny Morning Bowl",
    price: 88.09,
    category: "Bowl",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Golden Glow Bowl",
    price: 77.48,
    category: "Bowl",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Lemon Zest Bowl",
    price: 78.2,
    category: "Bowl",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunshine Delight Bowl",
    price: 97.38,
    category: "Bowl",
    color: "Yellow",
    img: "",
  },

  {
    quantity: "10",
    name: "Classic Elegance Vase",
    price: 53.26,
    category: "Vase",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Modern Simplicity Vase",
    price: 52.48,
    category: "Vase",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Snowy Day Vase",
    price: 66.12,
    category: "Vase",
    color: "White",
    img: "",
  },
  {
    quantity: "10",
    name: "Ocean Breeze Vase",
    price: 59.72,
    category: "Vase",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Azure Sky Vase",
    price: 88.45,
    category: "Vase",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Deep Sea Vase",
    price: 96.54,
    category: "Vase",
    color: "Blue",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunny Morning Vase",
    price: 63.65,
    category: "Vase",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Golden Glow Vase",
    price: 86.31,
    category: "Vase",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Lemon Zest Vase",
    price: 96.15,
    category: "Vase",
    color: "Yellow",
    img: "",
  },
  {
    quantity: "10",
    name: "Sunshine Delight Vase",
    price: 86.84,
    category: "Vase",
    color: "Yellow",
    img: "",
  },
];
